### ISSUE TITLE
Result count return nil value

### ISSUE THREAD

**Issue by stevenang** [codewinsdotcom/PostgresClientKit#11]
Hello 

I noticed the cursor.rowCount always return a nil.  Is that normal?

Here is my code:

`
let cursor = try SQL_STATEMENT!.execute(parameterValues: ["\(roleId)"])
NSLog("Row count \(String(describing: cursor.rowCount))")
`

This occurred in any select statement.

Thank you and good day.

**Comment by pitfield** [comment]
From the API doc:

"If this Cursor has one or more rows, this property is nil until the final row has been retrieved (in other words, until next() returns nil)."

**Comment by pitfield** [comment]
Please let me know or open a new issue if you have other questions about this.
