### ISSUE TITLE
Feature Request: Set application name in the Startup Message

### ISSUE THREAD

**Issue by kkieffer** [codewinsdotcom/PostgresClientKit#21]
When I run pgAdmin on a Postgres database server, it reports the "Application Name" for the client that connected - usually this is set by the application like JDBC, unless customized by the user. For a client connecting with this library, Application Name is blank.

I believe there is a "application_name" parameter that can be set in the Parameters of the Startup message.  It would be nice to let the user customize this, and provide a default if they don't (something like "PGClientKit").

**Comment by kkieffer** [comment]
I was able to add this in my fork and I tested, it works fine.  See changes here:

https://github.com/kkieffer/PostgresClientKit/commit/edb0647c8c10e5721bf7351581007c7eb8ca0618

**Comment by pitfield** [comment]
OK, thanks!  I'll incorporate this into the next release.

**Comment by pitfield** [comment]
Added an `applicationName` property to `ConnectionConfiguraition`.

**Comment by pitfield** [comment]
Available in v1.2.0.  Thanks again, @kkieffer!
