### ISSUE TITLE
Error 9989

### ISSUE THREAD

**Issue by NSCabezon** [codewinsdotcom/PostgresClientKit#23]
Hi! 
I'm getting the following error:
`[Connection-1 severe] Unable to connect socket: Error code: -9989(0x-2705), Operation not permitted`

my config looks like this

```
var configuration = PostgresClientKit.ConnectionConfiguration()
configuration.host = "localhost"
configuration.database = "recetas"
configuration.user = "postgres"
configuration.ssl = false
configuration.credential = Credential.trust
```

while this works:

<img width="441" alt="Captura de pantalla 2020-04-18 a las 0 07 33" src="https://user-images.githubusercontent.com/563761/79617798-a23f4b80-8108-11ea-8021-06ccc58e3016.png">

Any idea of what am I doing wrong?

**Comment by pitfield** [comment]
Your code snippet looks OK.  Are you able to connect using psql?  For example:

    psql -h localhost -p 5432 recetas postgres

Is the client app running on macOS or Linux?  If macOS, what version?  And are you running within Xcode, or a built application?

"Operation not permitted" sounds like the enhanced System Integrity Protection features in macOS.  I'm still on Mojave (10.14.6), but I understand that SIP is even more aggressive in Catalina.  If you are on Catalina, you might try *temporarily* disabling SIP using `csrutil` (as described [here](https://appletoolbox.com/seeing-error-operation-not-permitted-in-macos-mojave/)).

**Comment by NSCabezon** [comment]
I can, and other clients like "SQLPro for Postgres" app is able to connect. I'm in catalina, I'll look deeper into it... 

Thanks btw!

EDIT: it was indeed a permissions thing :)

**Comment by dirkwingenter** [comment]
I'm running in to the same issue in Monterey. Could you point me to how you resolved this?

**Comment by dirkwingenter** [comment]
After a little bit of reading and settings browsing and for the benefit of others:

Xcode project settings -> Targets: Signing / Capabilities -> App Sandbox -> Network - Outgoing connections
