### ISSUE TITLE
Result of executed statement

### ISSUE THREAD

**Issue by NSCabezon** [codewinsdotcom/PostgresClientKit#24]
Hi, maybe I don't know how to get it but, is it possible to retrieve the result after a statement is executed? I'm talking about other things than `Select` statements, for example If I execute an update statement I don't know how to get the number of rows affected...

**Comment by pitfield** [comment]
You can get this by accessing [Cursor.rowCount](https://codewinsdotcom.github.io/PostgresClientKit/Docs/API/Classes/Cursor.html#/s:17PostgresClientKit6CursorC8rowCountSiSgvp).

**Comment by NSCabezon** [comment]
great! thanks a lot!
