### ISSUE TITLE
Get server's error message

### ISSUE THREAD

**Issue by PerplexedFox** [codewinsdotcom/PostgresClientKit#25]
Hi,

I'm using PostgresClienKit in my app with a database that applies Serializable transaction isolation. I need to be able to get the server messages to provide the user with feedback, whether the aborted transaction was due to serialization or wrong data. 

I've seen there is a Notice struct, yet I couldn't find a way to get the (string) message. Can you help me?

**Comment by pitfield** [comment]
A `Notice` instance is an associated value of `PostgresError.sqlError`.  So the `catch` pattern is something like...

```
} catch PostgresError.sqlError(let notice) {
    // process the notice
    ...
} catch {
    // handle other types of errors
    ....
}
```

**Comment by PerplexedFox** [comment]
Thanks!
