### ISSUE TITLE
I'm sorry, my problem is still not resolved. My function start() opens session in Postgres database and I need to make this session still open. I checked the function prepareStatement, where is written "Any previous `Cursor` for this `Connection` is closed.". Is there a solution to keep the session open?

### ISSUE THREAD

**Issue by AMBIENTE1** [codewinsdotcom/PostgresClientKit#29]
I'm sorry, my problem is still not resolved. My function start() opens session in Postgres database and I need to make this session still open. I checked the function prepareStatement, where is written "Any previous `Cursor` for this `Connection` is closed.". Is there a solution to keep the session open?

_Originally posted by @AMBIENTE1 in https://github.com/codewinsdotcom/PostgresClientKit/issue_comments/711085413_

**Comment by pitfield** [comment]
Duplicate of #28.
