### ISSUE TITLE
SET Timezone

### ISSUE THREAD

**Issue by AMBIENTE1** [codewinsdotcom/PostgresClientKit#31]
Hello pitfield,

In my project Postgres server is located in Europe - Prague. When I use the select now () command, Postgres returns a datetime in GMT, but I need a datetime of +2 hours.
I could ask to adjust the SET TIMEZONE = 'GMT' to parameter SET TIMEZONE = + 2 or
SET TIMEZONE = 'Europe / Prague'  ?

Best regards
Carlos

**Comment by pitfield** [comment]
Here is my understanding of your question:  You have a `TIMESTAMP WITH TIME ZONE` value and want to generate a string representation in specific particular time zone.

Here are a couple of options:

In SQL, you can use the `AT TIME ZONE` construct, for example:

`SELECT now() AT TIME ZONE 'Europe/Prague';`

In Swift, you can use a `DateFormatter`, for example:

      let df = DateFormatter()
      df.dateFormat = "yyyy-MM-dd HH:mm:ss.SSSxxxxx"
      df.timeZone = TimeZone(identifier: "Europe/Prague")!

      ...

      let cursor = try statement.execute()
        
      for row in cursor {
          let columns = try row.get().columns
          let now = try columns[0].timestampWithTimeZone().date
          print(df.string(from: now)) // prints 2021-04-02 17:52:32.266+02:00
      }

Does this help?

**Comment by AMBIENTE1** [comment]
Yes, I know the possibilities of SQL.  In my PSQL database are many (11280) functions that assumes with a setting of GMT + 2 and which are inpossible to change. It is a database of Point of sale system.

I tried to change a timezone in the postgresql.conf file but PostgresClientKit error: Unable to connect socket: Error code: -9989(0x-2705)

Please is there any other solution?

**Comment by pitfield** [comment]
Please try picking up commit 2e504ae (head of develop branch).  This should allow you to set the TIMEZONE on a connection, for example `SET TIMEZONE='Europe/Prague';`.

**Comment by AMBIENTE1** [comment]
Thank you so much David. It helped a lot.

**Comment by pitfield** [comment]
Thanks for testing it Carlos.

Released in v1.4.0.
