### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by anurag1991** [codewinsdotcom/PostgresClientKit#32]
@pitfield pitfield  Thanks for providing such a great library for PostGress in swift.

I am actually trying to connect with the same DB you added into sample code and i am getting error.

▿ PostgresError
  ▿ socketError : 1 element
    ▿ cause : Error code: -9989(0x-2705), Connection refused
      - domain : "com.ibm.oss.Socket.ErrorDomain"
      - errorCode : -9989
      ▿ errorReason : Optional<String>
        - some : "Connection refused"
      - bufferSizeNeeded : 0

**Comment by pitfield** [comment]
This error indicates a problem creating a socket connection to the Postgres server.  I suggest double-checking the hostname and port number set in the ConnectionConfiguration instance, and check that hostname/port isn't being blocked by a firewall.

Can you connect to Postgres from the command line using psql? For example:

    psql --host 127.0.0.1 --port 5432 --dbname example --username bob

**Comment by anurag1991** [comment]
i figured it out @pitfield Appreciated your reply!

**Comment by dirkwingenter** [comment]
I'm running into the exact same issue. Any hint on what caused the error?
