### ISSUE TITLE
No such module 'PostgresClientKit'

### ISSUE THREAD

**Issue by stevenang** [codewinsdotcom/PostgresClientKit#4]
An error of No such module 'PostgresClientKit' occurred on the import PostgresClientKit.

The pod install command executed without any problem and there are 3 folders (BlueSocket, BlueSSLService and PostgresClientKit) added under Pods folder.  However, the error still occurred.

Can anyone help with this issue?

Thank you and good day.

**Comment by stevenang** [comment]
Additional information.  I found out there is an error in Connection.swift that said No such module 'Socket'

**Comment by stevenang** [comment]
Hello.  the problem was solved after I rebuild everything

**Comment by pitfield** [comment]
Glad you got it working.

I have also seen this error message when I accidentally opened the Xcode project (e.g. Foo.xcodeproj) in Xcode, when I should have opened the Xcode workspace (e.g. Foo.xcworkspace) generated by CocoaPods.
