### ISSUE TITLE
Project settings are valid but still get warning plus two other warnings

### ISSUE THREAD

**Issue by brenjack** [codewinsdotcom/PostgresClientKit#46]
<img width="1053" alt="Screenshot 2022-11-08 at 1 11 17 AM" src="https://user-images.githubusercontent.com/57248794/200358941-186ce6e3-c4f8-49dc-b732-fe77247f779b.png">

**Comment by brenjack** [comment]
I'm able to run in the simulator but just wanted a clean build. I'm a swift newbie but let me know if I can help in any way. I'm also available for virtual meetings in the evenings on Mondays and Wednesdays.

**Comment by pitfield** [comment]
It looks like you are using CocoaPods.  Are you consuming PostgresClientKit as a CocoaPod or through Swift Package Manager?

I was able to create a simple iOS app in Xcode today, successfully picking up PostgresClientKit as a CocoaPod.

You might try setting `platform` in your `Podfile`.  For example:

    target 'Delme4' do
      platform :ios, '16.1'
      pod 'PostgresClientKit', '~> 1.0'
    end

To clear three warnings in Xcode, I also had to bump up `IPHONEOS_DEPLOYMENT_TARGET` to 11.0 (from 10.0) in the `PostgresClientKit`, `BlueSocket`, and `BlueSSLService` targets of `Pods.xcodeproj`.

With this, I was able to get a clean build in my environment (Xcode 14.1 against an iOS 16.1 simulator).

I'm not sure any of this will help you, though -- in your warning messages, I don't know where the iOS 15.6 reference is coming from.  Other CocoaPods?

If you are still having problems, if you could create a GitHub repository with a simple reproducible test case, I could investigate further.

Also, I recommend Swift Package Manager for dependency management, whenever possible.  It's well integrated into Xcode now, and is pretty bulletproof.  Here is a simple iOS app that consumes PostgresClientKit through Swift Package Manager.

https://github.com/pitfield/PostgresClientKit-iOS-Example

**Comment by brenjack** [comment]
Okay, I think the best way to go is via Swift Package Manager (SPM). I trashed everything created a new xcode project. I git cloned this repo and did swift package clean and swift build. I then added the package to my project and import PostgresClientKit was not recognized. Here is the link to my public repo:

https://github.com/fmigsystems/DMPJ_Attendance

**Comment by pitfield** [comment]
Try this in Xcode:

- File / Add packages...
- Enter Package URL (top-right of dialog box): https://github.com/codewinsdotcom/PostgresClientKit
- Dependency Rule: Up to Next Major Version 1.0.0
- Click Add Package button
- Click Add Package

**Comment by brenjack** [comment]
Working! Runs in the simulator when 'import PostgresClientKit' is added. If it is alright with you, I'll create a more detailed mark down step by step page for xcode 14.

**Comment by pitfield** [comment]
Glad you got it working.  I've added a few notes to the README on consuming PostgresClientKit from an Xcode project.  Please let me know if you have any suggestions.  Thanks!
