### ISSUE TITLE
Connection error: "unsupported startup parameter: bytea_output"

### ISSUE THREAD

**Issue by mingchen** [codewinsdotcom/PostgresClientKit#48]
First thanks for this awesome kit.

When I use demo code in README to connect a server. I got following error:

```
"unsupported startup parameter: bytea_output"
```

Server info:
```
=> select version();
                                                        version                                                        
-----------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.14 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (Gentoo Hardened 9.3.0 p2) 9.3.0, 64-bit
(1 row)
```

I donot own the server so  donot the server config.

Search around and found those:

> The "fix" is to add this to the config.ini under the [pgbouncer] section:
> ignore_startup_parameters = extra_float_digits
> 
> https://stackoverflow.com/questions/36495062/pycharm-and-postgres-error-unsupported-startup-parameter-extra-float-digits

**Comment by pitfield** [comment]
The `bytea_output` parameter was introduced in PostgreSQL version 9.  PostgresClientKit has been setting it to `hex` since its first release, which was tested with PostgreSQL 10.

Any chance that Swift is connecting to a different (and older) version of Postgres than `psql`?

**Comment by mingchen** [comment]
I use the same host, port to connect, so should be the same server. I also checked the document about `bytea_output` but not sure why server complaint this but psql can success.

**Comment by pitfield** [comment]
I just installed Postgres 12.14 on an Ubuntu 22.04 VPS (Linode).  Using PostgresClientKit, I was able to successfully connect to the database (using [this sample code](https://github.com/pitfield/PostgresClientKit-CommandLine-Example)).

```
postgres@localhost:~$ psql
psql (12.14 (Ubuntu 12.14-1.pgdg22.04+1))
Type "help" for help.

postgres=# select version();
                                                               version                                                               
-------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.14 (Ubuntu 12.14-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
(1 row)

# swift run
Building for debugging...
Build complete! (0.10s)
San Francisco on 1994-11-27: low: 46, high: 50, precipitation: Optional(0.25)
San Francisco on 1994-11-29: low: 43, high: 57, precipitation: Optional(0.0)
```

At this point, I suggest you try a fresh Postgres install.

**Comment by pitfield** [comment]
Feel free to re-open this issue or file a new one if you are still getting this error and can provide the specific steps to reproduce it.
