### ISSUE TITLE
SCRAM-SHA-256 Support

### ISSUE THREAD

**Issue by jkatz** [codewinsdotcom/PostgresClientKit#5]
Hi! Thanks for writing this driver for Swift!

PostgreSQL has supported SCRAM-SHA-256 authentication since version 10 and the community is looking to make it the [default password-based authentication method](https://www.postgresql.org/message-id/flat/efcbd7a2-f7fb-6788-6d7f-f627ac838d4c%402ndquadrant.com) for version 13 (more than a year away, so there is some time). As such, I would strongly recommend to support it :smile:

A list of non-libpq based implementations that are implementing SCRAM can be found here: https://wiki.postgresql.org/wiki/List_of_drivers

I have some practice [implementing the method](https://github.com/MagicStack/asyncpg/pull/437) so I'm happy to help where needed.

**Comment by pitfield** [comment]
Thanks for the heads up on Postgres 13.  +1 to adding SCRAM-SHA-256 support.

Thanks also for the link to your Python client code for this.  That will definitely help.  I was getting tangled up in the web of RFCs.

**Comment by neilt** [comment]
I am also looking for this.  It seems that the Postgres community is considering holding off till 14 to make SCRAM the default, but during the discussion this project was the only driver mentioned that did not implement SCRAM support.

**Comment by pitfield** [comment]
Thanks for the heads up about possibly holding off to 14 to make SCRAM the default.  I found [the relevant thread](https://www.postgresql.org/message-id/flat/d5b0ad33-7d94-bdd1-caac-43a1c782cab2%402ndquadrant.com).

I'm hoping get SCRAM support into PostgresClientKit in the next few months.

**Comment by jkatz** [comment]
As a follow-up, SCRAM is now the official password default in [PG14](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=c7eab0e97e6cf1d0c136c22269c10ae11ba874c4) :grin: So there's about t-minus a year and change before the updated default is released (14 Beta 1 is ~May 2021).

I'm happy to answer any questions about SCRAM or the implementation. Here is a [higher-level overview of how it works](https://www.slideshare.net/jkatz05/get-your-insecure-postgresql-passwords-to-scram) in PostgreSQL.

**Comment by pitfield** [comment]
Nice slide deck!

I started working on this last week.  One question for you, @jkatz:  In the [PR you mentioned earlier](https://github.com/MagicStack/asyncpg/pull/437), you mention:

    PostgreSQL 11 added support for the channel binding (i.e.
    SCRAM-SHA-256-PLUS) but to do some ongoing discussion, there is a conscious
    decision by several driver authors to not support it as of yet.
 
Could you elaborate, or suggest where I could get more details on this decision?  Is this because the underlying SSL stack may not provide APIs to retrieve the TLS FinishedMessage (for tls-unique) or server certificate (for tls-server-end-point)?  (I noticed that the Postgres server now only supports tls-server-end-point.)

Thanks!

**Comment by pitfield** [comment]
SCRAM-SHA-256 authentication is available in v1.3.0.

**Comment by jkatz** [comment]
@pitfield Oops I missed the question, sorry! Congrats!!!
