### ISSUE TITLE
Any support for NOTIFICATIONS ?

### ISSUE THREAD

**Issue by duncangroenewald** [codewinsdotcom/PostgresClientKit#52]
Presumably this library does not support asynchronous notifications as per https://www.postgresql.org/docs/current/libpq-notify.html.

Any plan to support this or any suggestion as to feasibility of implementing support for this ?

**Comment by pitfield** [comment]
Yes, the library does currently support this.  Take a look at the `ConnectionDelegate` protocol and, for a usage example, `ConnectionDelegateTest`.
