### ISSUE TITLE
Getting Socket connect error

### ISSUE THREAD

**Issue by haridass-pdx** [codewinsdotcom/PostgresClientKit#53]
first time using this package 
just trying to use the example 

Getting this error continually.  
Can connect to Postgres w/ psql with same parameters no problem

MacOS = 14.6
postgres vers 17 
 Xcode = 16.1
swift version 5

[2024-11-03T05:10:57.039Z Connection-1 severe] Unable to connect socket: Error code: -9989(0x-2705), Operation not permitted
socketError(cause: Error code: -9989(0x-2705), Operation not permitted)

any help would be appreciated.

**Comment by pitfield** [comment]
Please see the final comment on #23.  Does that help?

https://github.com/codewinsdotcom/PostgresClientKit/issues/23#issuecomment-974779654

**Comment by haridass-pdx** [comment]
Yes that was exactly the issue not enabling network connections in sandboxing

Thanks

**Comment by freddy366** [comment]
I have the same issue with:
         Socket-Fehler: -9989 - Optional("Operation not permitted")

I already activated the network connection in and out.

i use this code to test the connection but every time i get this error: 

func testConnection() {
        do {
            let socket = try Socket.create()
            try socket.connect(to: "40.101.64.66", port: 587)
            print("Verbindung erfolgreich hergestellt!")
            connectionTestResult = "Verbindung erfolgreich hergestellt!"
            connectionTestColor = .green
        } catch let error as Socket.Error {
            // Spezifische Fehlerbehandlung für Socket.Error
            print("Socket-Fehler: \(error.errorCode) - \(error.errorReason)")
            connectionTestResult = "Socket-Fehler: \(error.errorCode) - \(error.errorReason)"
            connectionTestColor = .red

If i use an Hostname i get:
-9989 - Optional("nodename nor servname provided, or not known")

Does anyone know where I took the wrong turn?
