### ISSUE TITLE
Can't INSERT

### ISSUE THREAD

**Issue by Matovsky** [codewinsdotcom/PostgresClientKit#6]
Hello. I can only SELECT data from server, but cannot INSERT or update. Am I right?

**Comment by pitfield** [comment]
INSERT, UPDATE, etc. should all work.  Please take a look at Tests/PostgresClientKitTests/SQLStatementTest.swift, around line 65, for an example.

https://github.com/codewinsdotcom/PostgresClientKit/blob/master/Tests/PostgresClientKitTests/SQLStatementTest.swift

**Comment by Matovsky** [comment]
> INSERT, UPDATE, etc. should all work. Please take a look at Tests/PostgresClientKitTests/SQLStatementTest.swift, around line 65, for an example.
> 
> https://github.com/codewinsdotcom/PostgresClientKit/blob/master/Tests/PostgresClientKitTests/SQLStatementTest.swift

Thank you very much!
