### ISSUE TITLE
Incorrect data retrieved.

### ISSUE THREAD

**Issue by stevenang** [codewinsdotcom/PostgresClientKit#9]
I have some data save in Postgre SQL as TEXT and I tried to retrieved those data using column[].string() method.  However, the retrieved data didn't match with what I have in database.

Can anyone help?

Here is what I have in database (partial data)
`
iVBORw0KGgoAAAANSUhEUgAADBAAAAkMCAIAAAB7B33CAAABYWlDQ1BrQ0dDb2xv
clNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAO
hLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw
1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI
+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOU
pFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrv
MzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNy
BgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDz
`

and here is what I have using column[].string()
`
\x6956424f5277304b47676f414141414e53556845556741414442414141416b4d4341494141414237423333434141414259576c445131427251306444623278760d0a636c4e7759574e6c52476c7a634778686556417a4141416f6b574e6759464a4a4c436a4959574667594d6a4e4b796b4b636e64536949694d556d422f794d414f0d0a684c774d5967774b69636e4642593442415435414a5177774768563875386241434b497636344c4d4f69553174556d31587344585971627731597576524a73770d0a31614d4172705455346d51672f51654955354d4c696b6f59474
`

Thank you and good day.

**Comment by pitfield** [comment]
The bottom looks like a hex encoding of the ASCII characters in the top.

Could you please provide a standalone test case that reproduces the problem?

**Comment by stevenang** [comment]
Here is what i did:

1. Convert Image as what you did

`
if let imageData = self.patientImageView.image!.pngData()?.base64EncodedData(options: .lineLength64Characters) {
    NSLog("Image Data size: \(imageData.count)")
     NSLog("Image Data: \(imageData)")
     patient.image = String(data: imageData, encoding: .ascii)!
     NSLog("Data size: \(patient.image!.count)")
     NSLog("Data: \(patient.image)")
                }
`
2. Insert the string data to database
3. Select the inserted data using column[].string()

I check both DB and the result of the select statement after these 3 steps.

**Comment by pitfield** [comment]
I need the details of steps 2 and 3.  Could you please provide a standalone test case, like the `main.swift` file I posted in Issue #8?

**Comment by stevenang** [comment]
Hello

It seems my mistake in this part.  I just notice that the column I tried to retrieved was defined as BYTEA not TEXT.  and it works well now after I change to TEXT.

I will close this problem for now. 

Thanks for the help,
